# This file trains and tests the RNN in inference.py with data sets generated by models.py

from inference_threshold_testing import *
from models_single_product import *

RD.seed()



if __name__ == '__main__':

    dynamics = market(settings.params)

    model = RNN()

    model.empty_losses()

    print('pretraining performance on the traning set')

    # training_sample1 = dynamics.genTorchDataset(LOAD=True, filename='toy_dataset.pkl')
    # training_sample2 = dynamics.genTorchDataset(LOAD=True, filename='toy_dataset2_4000.pkl')
    # training_sample3 = dynamics.genTorchDataset(LOAD=True, filename='toy_dataset3_10000.pkl')
    # training_sample4 = dynamics.genTorchDataset(LOAD=True, filename='toy_dataset4_14000.pkl')
    # training_sample5 = dynamics.genTorchDataset(LOAD=True, filename='toy_dataset5_20000.pkl')

    training_sample6 = dynamics.genTorchDataset(500,SAVE=True,filename='dataset6_5000_B0067PLM5E.pkl')
    # training_sample = training_sample1 + training_sample2 + training_sample3 + training_sample4 + training_sample5

    # training_sample6x = training_sample + training_sample + training_sample + training_sample  + training_sample  + training_sample \
    #                     + training_sample + training_sample + training_sample + training_sample + training_sample + training_sample \
    #                     + training_sample + training_sample

    # print(training_sample)
    print(100 * model.evaluateAveragePerformance(training_sample6))

    print('doTraining on the traning set')

    model.doTraining(training_sample6, batch_size = settings.BATCH_SIZE, window_length_loss=16, verbose = True ,
                     save = True , file_name = 'model_tuned_B0067PLM5E.pkl')
    print('perforamce on Trainging set AFTER')
    print(100 * model.evaluateAveragePerformance(training_sample6))
    model.plot_losses()
    model.save_losses()
    print(model.training_losses)


    print('performance on Test set after training')

    test_sample = dynamics.genTorchDataset(100)
    print(100 * model.evaluateAveragePerformance(test_sample))

