FROM gcr.io/deeplearning-platform-release/pytorch-gpu

# Install other required packages
RUN pip install sbi hyperopt mlflow tqdm arviz black nb_black pyreadr mypy

# Make a data folder which will be connected to the host
RUN mkdir /data
