# This file trains and tests the RNN in inference.py with data sets generated by models.py

from inference_ABC import *
from models_single_product import *

RD.seed()

if __name__ == '__main__':

    true_theta = 1
    prior_theta = np.linspace(0, 2, 100)
    gen_model = ABC_GenerativeModel(params={}, conditioning=False, direction=None)
    probability_above = gen_model.compute_direction_probability(dataset_size=50)
    print('probability_above is:', probability_above)
    obsreved_data = gen_model.generate_data(true_theta)
    print('obsreved_data', obsreved_data)
    (posterior, distances,
     accepted_count, trial_count,
     epsilon) = basic_abc(gen_model, obsreved_data, epsilon=0.2, min_samples=10)
    print('posterior',posterior)
    print('distances', distances)
    print('accepted_count', accepted_count)
    print('trial_count', trial_count)
    print('epsilon', epsilon)
    print(np.mean(posterior))









